services:
  app-service:
    build:
      context: ./app-service # specify directory where local Dockerfile is located
    ports:
      - "8000:8000"
  auth-service:
    build:
      context: ./auth-service # specify directory where local Dockerfile is located
    ports:
      - "3001:3000"  # Map localhost:3001 to container:3000